// <auto-generated />
namespace Solution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Migration2MayssaEvent_Company_Offre_CompanyConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration2MayssaEvent_Company_Offre_CompanyConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201910262306116_Migration2MayssaEvent_Company_Offre_CompanyConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
