// <auto-generated />
namespace Solution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Modif_Offer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modif_Offer));
        
        string IMigrationMetadata.Id
        {
            get { return "201910290834577_Modif_Offer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
